<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57469" started-at="2019-11-29T12:30:03Z" finished-at="2019-11-29T12:31:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57469" started-at="2019-11-29T12:30:03Z" finished-at="2019-11-29T12:31:01Z">
      <class name="org.Sample.tng.NextApp">
        <test-method status="PASS" signature="startTime()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="startTime" is-config="true" duration-ms="114" started-at="2019-11-29T18:00:03Z" finished-at="2019-11-29T18:00:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="PASS" signature="initalisation()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="initalisation" is-config="true" duration-ms="40119" started-at="2019-11-29T18:00:03Z" finished-at="2019-11-29T18:00:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initalisation -->
        <test-method status="PASS" signature="firstMethod()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="firstMethod" is-config="true" duration-ms="6085" started-at="2019-11-29T18:00:44Z" finished-at="2019-11-29T18:00:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstMethod -->
        <test-method status="FAIL" signature="aditaMain1(java.lang.String, java.lang.String)[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="aditaMain1" duration-ms="1244" started-at="2019-11-29T18:00:50Z" data-provider="multiple" finished-at="2019-11-29T18:00:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[soundarrajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9865107296]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [https://www.adactin.com/HotelApp/] but found [https://www.adactin.com/HotelApp/SearchHotel.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://www.adactin.com/HotelApp/] but found [https://www.adactin.com/HotelApp/SearchHotel.php]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.Sample.tng.NextApp.aditaMain1(NextApp.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aditaMain1 -->
        <test-method status="PASS" signature="firstMethod()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="firstMethod" is-config="true" duration-ms="446" started-at="2019-11-29T18:00:51Z" finished-at="2019-11-29T18:00:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstMethod -->
        <test-method status="FAIL" signature="aditaMain1(java.lang.String, java.lang.String)[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="aditaMain1" duration-ms="888" started-at="2019-11-29T18:00:51Z" data-provider="multiple" finished-at="2019-11-29T18:00:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9865105007]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[soundarrajan]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [https://www.adactin.com/HotelApp/] but found [https://www.adactin.com/HotelApp/SearchHotel.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://www.adactin.com/HotelApp/] but found [https://www.adactin.com/HotelApp/SearchHotel.php]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.Sample.tng.NextApp.aditaMain1(NextApp.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aditaMain1 -->
        <test-method status="PASS" signature="firstMethod()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="firstMethod" is-config="true" duration-ms="462" started-at="2019-11-29T18:00:52Z" finished-at="2019-11-29T18:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstMethod -->
        <test-method status="PASS" signature="aditaMain1(java.lang.String, java.lang.String)[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="aditaMain1" duration-ms="2690" started-at="2019-11-29T18:00:53Z" data-provider="multiple" finished-at="2019-11-29T18:00:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[soundarrajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mssoundar09]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aditaMain1 -->
        <test-method status="FAIL" signature="secondPage()[pri:0, instance:org.Sample.tng.NextApp@7d417077]" name="secondPage" is-config="true" duration-ms="0" started-at="2019-11-29T18:00:55Z" finished-at="2019-11-29T18:00:55Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at org.Sample.tng.NextApp.secondPage(NextApp.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:1012)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondPage -->
      </class> <!-- org.Sample.tng.NextApp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
